# Generated by Django 3.2.4 on 2021-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataxml',
            name='date',
        ),
        migrations.AlterField(
            model_name='dataxml',
            name='xml_base64',
            field=models.TextField(),
        ),
    ]
