# Generated by Django 3.2.4 on 2021-06-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210604_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataxml',
            name='status',
        ),
    ]
