# Generated by Django 3.2.4 on 2021-06-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dataxml_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataxml',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
